import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import { OrbitControls, Float, Sparkles, Ring, Torus, Sphere, useGLTF, Html, ContactShadows } from "@react-three/drei";
import * as THREE from "three";
import * as SkeletonUtils from "three/examples/jsm/utils/SkeletonUtils.js";
import { useSarahStore, AvatarPose } from "@/stores/useSarahStore";
import type { AvatarSpeechCue } from "@/lib/api";
import sarahGoldIdle from "@/assets/sarah-goldstandard-idle.png";
import sarahGoldFocused from "@/assets/sarah-goldstandard-focused.png";
import sarahGoldListening from "@/assets/sarah-goldstandard-listening.png";
import sarahGoldHappy from "@/assets/sarah-goldstandard-happy.png";

/**
 * AvatarSpec:
 * v9.0.9 production-mesh viewport note:
 * - AvatarPanel now treats the GLB/GLTF lane as the primary 3D runtime whenever a model URL exists.
 * - GoldStandard images remain visual references and emergency fallback cards only.
 * - The panel must display the real skinned/production mesh, with orbit/zoom available for inspection.
 * v9.0.7 shader-bound suit visual note:
 * - GLB clips are not auto-played.
 * - The runtime stays in rest-pose until modular hair/neon/boots are fully rig-bound.
 * - This is the “contract” the backend can evolve without breaking the UI.
 * - Start simple: modelUrl + backgroundUrl + pose + expression + speaking/listening.
 * - Later: add blendshapes, motion files, rigs, IK targets, etc.
 */
export type AvatarRenderMode = "procedural_holo" | "gltf_model" | "video_sprite" | "gold_standard_avatar";

export type AvatarSpec = {
  renderMode?: AvatarRenderMode;

  // 3D / media assets (generated by CanvasStudio / VideoEditorCore)
  modelUrl?: string; // GLB/GLTF file URL
  videoUrl?: string; // MP4/WebM for sprite mode (or for “hologram footage”)
  backgroundUrl?: string; // image/video background override
  backgroundType?: "none" | "image" | "video";

  // gold-standard AvatarPanel visual surface
  goldStandardUrl?: string;
  goldStandardIdleUrl?: string;
  goldStandardFocusedUrl?: string;
  goldStandardListeningUrl?: string;
  goldStandardHappyUrl?: string;
  goldStandardScale?: number;
  goldStandardYOffset?: number;
  meshFallbackUrl?: string;
  runtimeVisualPriority?: "gold_standard" | "gltf_model" | "auto" | string;
  forceMeshRuntime?: boolean;
  goldReferenceOnly?: boolean;
  authoringPolyTarget?: number;
  runtimeLod?: "preview" | "runtime" | "showcase" | "cinematic_2m" | "goldstandard_entity" | string;
  productionAssetContract?: string;
  blueprintConstructReady?: boolean;
  visualEffectsMode?: "off" | "secondary" | "full" | string;

  // behavior
  pose?: AvatarPose;
  gesture?: "none" | "wave" | "point" | "nod" | "shake" | "walk" | "turn_left" | "turn_right";
  lookAt?: { x: number; y: number; z: number }; // optional target in scene space

  // facial / expression
  expression?: string;
  speaking?: boolean;
  listening?: boolean;
  thinking?: boolean;

  // humanoid visual body profile: software anatomy/rig targets only
  bodyProfile?: {
    profile_name?: string;
    height_m?: number;
    weight_kg_visual_target?: number;
    head_height_ratio?: number;
    shoulder_width_ratio?: number;
    hip_width_ratio?: number;
    leg_length_ratio?: number;
    arm_span_ratio?: number;
    center_of_mass_y_ratio?: number;
    rig_units?: string;
    biological_plausibility?: string;
    robot_mapping_status?: string;
  };
  loaderState?: string;
  quality?: "preview" | "balanced" | "high" | "ultra" | "cinematic_2m" | "goldstandard_entity" | string;
  fpsCap?: number;
  lightingProfile?: "balanced" | "high_end" | string;
  shadowQuality?: "off" | "medium" | "high" | string;
  stageOffsetY?: number;
  avatarOffsetY?: number;
  useRuntimeStage?: boolean;
  materialMode?: "balanced" | "high_end" | string;

  // lip sync
  speechCues?: AvatarSpeechCue[];
  speechStartTime?: number | null;
};

interface Avatar3DProps {
  speaking?: boolean;
  listening?: boolean;
  expression?: string;

  /**
   * Optional spec coming from backend:
   * - If omitted, we fall back to procedural hologram.
   */
  spec?: AvatarSpec;
}

/* -----------------------------
   Holographic palette
------------------------------ */
const HOLO_PRIMARY = "#00d4ff";
const HOLO_SECONDARY = "#00ffcc";
const HOLO_DARK = "#0a1520";
const HOLO_MID = "#102030";
const HOLO_ACCENT = "#00b8d4";
const HOLO_GLOW = "#40e0d0";

function isCinematicQuality(value?: string) {
  const q = String(value || "").toLowerCase();
  return q === "cinematic_2m" || q === "goldstandard_entity" || q === "ultra" || q === "production" || q === "goldstandard";
}

function isHighOrBetterQuality(value?: string) {
  const q = String(value || "").toLowerCase();
  return isCinematicQuality(q) || q === "high";
}

function qualityDpr(value?: string): [number, number] {
  if (String(value || "").toLowerCase() === "goldstandard_entity") return [3.0, 4.0];
  if (isCinematicQuality(value)) return [2.5, 4.0];
  if (String(value || "").toLowerCase() === "high") return [2.0, 3.0];
  if (String(value || "").toLowerCase() === "preview") return [1.0, 1.35];
  return [1.2, 1.9];
}

function qualityShadowSize(value?: string) {
  if (String(value || "").toLowerCase() === "goldstandard_entity") return 8192;
  if (isCinematicQuality(value)) return 8192;
  if (String(value || "").toLowerCase() === "high") return 4096;
  return 1536;
}

function qualityToneExposure(value?: string) {
  if (String(value || "").toLowerCase() === "goldstandard_entity") return 1.62;
  if (isCinematicQuality(value)) return 1.56;
  if (String(value || "").toLowerCase() === "high") return 1.36;
  return 1.24;
}

/* -----------------------------
   Small utilities
------------------------------ */
function clamp01(v: number) {
  return Math.max(0, Math.min(1, v));
}

function easeInOut(t: number) {
  return t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2;
}

function isSarahStageObject(name: string) {
  return /stage|grid|floor|microstage/i.test(String(name || ""));
}

function classifySarahMaterial(meshName: string, materialName?: string) {
  const key = `${meshName || ""} ${materialName || ""}`.toLowerCase();
  if (isSarahStageObject(key)) return "stage";
  if (/neon|circuit|trim|glow/.test(key)) return "neon";
  if (/suit|body|boot|glove|pants|shirt/.test(key)) return "suit";
  if (/skin|head|face|lip|brow|lash|tooth|eye|iris/.test(key)) return "organic";
  if (/hair/.test(key)) return "hair";
  return "default";
}

function convertSarahMaterial(mat: any) {
  if (!mat) return mat;
  if (mat.isMeshPhysicalMaterial || mat.isMeshStandardMaterial) return mat;

  const next = new THREE.MeshPhysicalMaterial({
    name: mat.name || "",
    color: mat.color?.clone?.() || new THREE.Color("#ffffff"),
    map: mat.map || null,
    normalMap: mat.normalMap || null,
    roughnessMap: mat.roughnessMap || null,
    metalnessMap: mat.metalnessMap || null,
    emissiveMap: mat.emissiveMap || null,
    alphaMap: mat.alphaMap || null,
    aoMap: mat.aoMap || null,
    envMap: mat.envMap || null,
    transparent: !!mat.transparent,
    opacity: typeof mat.opacity === "number" ? mat.opacity : 1,
    side: mat.side ?? THREE.FrontSide,
    depthWrite: mat.depthWrite ?? true,
    depthTest: mat.depthTest ?? true,
  });

  next.emissive = mat.emissive?.clone?.() || new THREE.Color("#000000");
  next.emissiveIntensity = typeof mat.emissiveIntensity === "number" ? mat.emissiveIntensity : 1;
  next.roughness = typeof mat.roughness === "number" ? mat.roughness : 0.55;
  next.metalness = typeof mat.metalness === "number" ? mat.metalness : 0.0;
  next.alphaTest = typeof mat.alphaTest === "number" ? mat.alphaTest : 0;
  next.polygonOffset = !!mat.polygonOffset;
  next.polygonOffsetFactor = typeof mat.polygonOffsetFactor === "number" ? mat.polygonOffsetFactor : 0;
  next.polygonOffsetUnits = typeof mat.polygonOffsetUnits === "number" ? mat.polygonOffsetUnits : 0;
  (next as any).skinning = !!mat.skinning;
  (next as any).morphTargets = !!mat.morphTargets;
  (next as any).morphNormals = !!mat.morphNormals;
  return next;
}

function enhanceSarahMaterial(mesh: THREE.Mesh, materialMode: "balanced" | "high_end" = "balanced") {
  const material = mesh.material as THREE.Material | THREE.Material[] | undefined;
  const mats = (Array.isArray(material) ? material : material ? [material] : []).map((mat) => convertSarahMaterial(mat as any));
  if (Array.isArray(material)) {
    mesh.material = mats as THREE.Material[];
  } else if (mats[0]) {
    mesh.material = mats[0] as THREE.Material;
  }

  if ((mesh.geometry as any)?.computeVertexNormals) {
    (mesh.geometry as any).computeVertexNormals();
    if ((mesh.geometry as any).attributes?.normal) {
      (mesh.geometry as any).attributes.normal.needsUpdate = true;
    }
  }

  mats.forEach((mat: any) => {
    if (!mat) return;
    const role = classifySarahMaterial(mesh.name, mat.name);
    const highEnd = materialMode === "high_end";

    mat.needsUpdate = true;
    mat.toneMapped = role === "neon" ? false : true;
    mat.shadowSide = THREE.FrontSide;

    if (role === "suit") {
      if (mat.color) mat.color.set("#02050a");
      if (typeof mat.metalness === "number") mat.metalness = Math.max(mat.metalness, highEnd ? 0.52 : 0.34);
      if (typeof mat.roughness === "number") mat.roughness = Math.min(mat.roughness, highEnd ? 0.07 : 0.11);
      if (typeof mat.clearcoat === "number") mat.clearcoat = Math.max(mat.clearcoat, highEnd ? 1.0 : 0.9);
      if (typeof mat.clearcoatRoughness === "number") mat.clearcoatRoughness = Math.min(mat.clearcoatRoughness, highEnd ? 0.018 : 0.032);
      if (typeof mat.reflectivity === "number") mat.reflectivity = Math.max(mat.reflectivity, 0.7);
      if (typeof mat.envMapIntensity === "number") mat.envMapIntensity = Math.max(mat.envMapIntensity, highEnd ? 3.2 : 2.4);
      if (mat.emissive) mat.emissive.set("#02121d");
      if (typeof mat.emissiveIntensity === "number") mat.emissiveIntensity = Math.max(mat.emissiveIntensity, 0.11);
    } else if (role === "neon") {
      if (mat.color) mat.color.set("#d9ffff");
      if (mat.emissive) mat.emissive.set("#5cf4ff");
      if (typeof mat.emissiveIntensity === "number") mat.emissiveIntensity = Math.max(mat.emissiveIntensity, highEnd ? 6.8 : 5.6);
      if (typeof mat.roughness === "number") mat.roughness = Math.min(mat.roughness, 0.15);
      if (typeof mat.metalness === "number") mat.metalness = Math.max(mat.metalness, 0.1);
      mat.depthWrite = true;
      mat.depthTest = true;
      mat.side = THREE.FrontSide;
      // Keep the suit trim visually surface-bound: only a very tiny offset is
      // used so we reduce z-fighting without letting the cyan rails float away.
      mat.polygonOffset = true;
      mat.polygonOffsetFactor = -0.01;
      mat.polygonOffsetUnits = -0.01;
    } else if (role === "hair") {
      if (mat.color && !mat.map) mat.color.set("#201018");
      if (typeof mat.roughness === "number") mat.roughness = Math.min(mat.roughness, highEnd ? 0.18 : 0.28);
      if (typeof mat.metalness === "number") mat.metalness = Math.max(mat.metalness, 0.08);
      if (typeof mat.clearcoat === "number") mat.clearcoat = Math.max(mat.clearcoat, highEnd ? 0.55 : 0.35);
      if (typeof mat.envMapIntensity === "number") mat.envMapIntensity = Math.max(mat.envMapIntensity, highEnd ? 1.8 : 1.15);
      mat.side = THREE.DoubleSide;
    } else if (role === "organic") {
      if (mat.color && !mat.map) mat.color.set("#f0bca8");
      if (typeof mat.roughness === "number") mat.roughness = Math.min(Math.max(mat.roughness, 0.30), highEnd ? 0.42 : 0.5);
      if (typeof mat.metalness === "number") mat.metalness = Math.min(mat.metalness, 0.04);
      if (typeof mat.clearcoat === "number") mat.clearcoat = Math.max(mat.clearcoat, highEnd ? 0.28 : 0.12);
      if (typeof mat.envMapIntensity === "number") mat.envMapIntensity = Math.max(mat.envMapIntensity, highEnd ? 1.18 : 0.92);
      if (mat.color && mesh.name.toLowerCase().includes("head")) {
        mat.color.offsetHSL(0, 0.02, 0.025);
      }
    } else if (role === "stage") {
      if (mat.color) mat.color.set(isSarahStageObject(mesh.name) && /grid/i.test(mesh.name) ? "#5ae8ff" : "#05070d");
      if (typeof mat.metalness === "number") mat.metalness = /grid/i.test(mesh.name) ? 0.28 : 0.48;
      if (typeof mat.roughness === "number") mat.roughness = /grid/i.test(mesh.name) ? 0.24 : 0.74;
      if (mat.emissive) mat.emissive.set(/grid/i.test(mesh.name) ? "#0f718a" : "#000000");
      if (typeof mat.emissiveIntensity === "number") mat.emissiveIntensity = /grid/i.test(mesh.name) ? 0.18 : 0;
    }
  });
}

/* -----------------------------
   Scene background (inside R3F)
   - supports image/video as a plane behind avatar
------------------------------ */
function SceneBackground({ url, type }: { url?: string; type?: "image" | "video" | "none" }) {
  const meshRef = useRef<THREE.Mesh>(null);

  const texture = useMemo(() => {
    if (!url || type === "none") return null;

    if (type === "image") {
      const tex = new THREE.TextureLoader().load(url);
      tex.colorSpace = THREE.SRGBColorSpace;
      return tex;
    }

    if (type === "video") {
      const video = document.createElement("video");
      video.src = url;
      video.muted = true;
      video.loop = true;
      video.playsInline = true;
      video.autoplay = true;
      video.crossOrigin = "anonymous";
      video.play().catch(() => {
        // Autoplay might be blocked until user gesture; it’s okay.
      });
      const tex = new THREE.VideoTexture(video);
      tex.colorSpace = THREE.SRGBColorSpace;
      return tex;
    }

    return null;
  }, [url, type]);

  useFrame(({ camera }) => {
    if (!meshRef.current) return;
    // keep background plane “stuck” behind camera
    const z = -6;
    const dir = new THREE.Vector3();
    camera.getWorldDirection(dir);
    const pos = camera.position.clone().add(dir.multiplyScalar(8));
    meshRef.current.position.copy(pos);
    meshRef.current.quaternion.copy(camera.quaternion);
    meshRef.current.translateZ(z);
  });

  if (!texture) return null;

  return (
    <mesh ref={meshRef}>
      <planeGeometry args={[20, 12]} />
      <meshBasicMaterial map={texture} transparent opacity={0.7} depthWrite={false} />
    </mesh>
  );
}

/* -----------------------------
   Ring FX
------------------------------ */
function HoloRing({ radius, speed, color, yPos = 0 }: { radius: number; speed: number; color: string; yPos?: number }) {
  const ringRef = useRef<THREE.Mesh>(null);

  useFrame((state) => {
    if (ringRef.current) ringRef.current.rotation.z = state.clock.elapsedTime * speed;
  });

  return (
    <Ring ref={ringRef} args={[radius, radius + 0.015, 64]} position={[0, yPos, 0]} rotation={[Math.PI / 2, 0, 0]}>
      <meshBasicMaterial color={color} transparent opacity={0.4} side={THREE.DoubleSide} />
    </Ring>
  );
}

/* -----------------------------
   Procedural Hologram Avatar
   - you can keep your current geometry style
   - but now it’s driven by pose/gesture/spec
------------------------------ */
function ProceduralHoloAvatar({
  expression,
  speaking,
  listening,
  speechCues,
  speechStartTime,
  pose,
  gesture,
  mouseTarget,
}: {
  expression: string;
  speaking: boolean;
  listening: boolean;
  speechCues: AvatarSpeechCue[];
  speechStartTime: number | null;
  pose: AvatarPose;
  gesture?: AvatarSpec["gesture"];
  mouseTarget: { x: number; y: number };
}) {
  const groupRef = useRef<THREE.Group>(null);
  const glowRef = useRef<THREE.Mesh>(null);

  const [mouthOpen, setMouthOpen] = useState(0);
  const [eyeBlink, setEyeBlink] = useState(0);
  const [squint, setSquint] = useState(0);

  // gesture animator (simple front-end placeholder — backend can later send motion clips)
  const gestureRef = useRef<{ t0: number; active: boolean }>({ t0: 0, active: false });

  // expression → color (you can expand)
  const primaryColor = useMemo(() => {
    switch (expression) {
      case "happy":
        return "#00ffcc";
      case "sad":
        return "#00a8ff";
      case "angry":
        return "#00ffaa";
      case "surprised":
        return "#00e8d4";
      default:
        return HOLO_PRIMARY;
    }
  }, [expression]);

  // lip sync
  useEffect(() => {
    if (!speaking) {
      setMouthOpen(0);
      return;
    }

    if (speechCues.length > 0 && speechStartTime) {
      const interval = setInterval(() => {
        const elapsed = Date.now() - speechStartTime;
        let cueValue = 0;

        for (let i = 0; i < speechCues.length; i++) {
          if (speechCues[i].t <= elapsed) {
            cueValue = speechCues[i].v;
          } else {
            if (i > 0) {
              const prev = speechCues[i - 1];
              const next = speechCues[i];
              const t = (elapsed - prev.t) / Math.max(1, next.t - prev.t);
              cueValue = prev.v + (next.v - prev.v) * t;
            }
            break;
          }
        }
        setMouthOpen(clamp01(cueValue));
      }, 33);
      return () => clearInterval(interval);
    }

    // fallback oscillation
    const interval = setInterval(() => {
      const time = Date.now() / 1000;
      const base = Math.sin(time * 8) * 0.25 + 0.3;
      const variation = Math.sin(time * 12) * 0.1;
      setMouthOpen(clamp01(base + variation));
    }, 50);

    return () => clearInterval(interval);
  }, [speaking, speechCues, speechStartTime]);

  // blinking
  useEffect(() => {
    const blink = () => {
      setEyeBlink(1);
      setTimeout(() => setEyeBlink(0), 120 + Math.random() * 60);
    };
    const schedule = () => {
      const delay = 2500 + Math.random() * 3500;
      const timer = setTimeout(() => {
        blink();
        schedule();
      }, delay);
      return timer;
    };
    const timer = schedule();
    return () => clearTimeout(timer);
  }, []);

  // listening squint
  useEffect(() => setSquint(listening ? 0.2 : 0), [listening]);

  // gesture trigger
  useEffect(() => {
    if (gesture === "wave") {
      gestureRef.current = { t0: performance.now(), active: true };
    }
  }, [gesture]);

  useFrame((state) => {
    if (groupRef.current) {
      // float
      groupRef.current.position.y = Math.sin(state.clock.elapsedTime * 0.8) * 0.025;

      // mouse follow
      const targetYaw = mouseTarget.x * 0.3;
      const targetPitch = mouseTarget.y * 0.15;
      groupRef.current.rotation.y = THREE.MathUtils.lerp(groupRef.current.rotation.y, targetYaw, 0.05);

      const basePitch = listening ? 0.06 : 0;
      groupRef.current.rotation.x = THREE.MathUtils.lerp(groupRef.current.rotation.x, basePitch + targetPitch, 0.04);

      // pose offsets (very light placeholders)
      const poseY = pose === "sit" ? -0.15 : 0;
      groupRef.current.position.y += poseY;

      // wave (arm swing placeholder)
      if (gestureRef.current.active) {
        const dt = (performance.now() - gestureRef.current.t0) / 1000;
        const phase = clamp01(dt / 1.2);
        if (phase >= 1) gestureRef.current.active = false;

        // rotate whole avatar slightly as “acknowledgement”
        const a = Math.sin(dt * 10) * 0.04 * (1 - phase);
        groupRef.current.rotation.z = THREE.MathUtils.lerp(groupRef.current.rotation.z, a, 0.2);
      } else {
        groupRef.current.rotation.z = THREE.MathUtils.lerp(groupRef.current.rotation.z, 0, 0.05);
      }
    }

    if (glowRef.current) {
      const material = glowRef.current.material as THREE.MeshBasicMaterial;
      material.opacity = 0.06 + Math.sin(state.clock.elapsedTime * 2) * 0.03;
    }
  });

  return (
    <Float speed={1.2} rotationIntensity={0.08} floatIntensity={0.15}>
      <group ref={groupRef}>
        <Sphere ref={glowRef} args={[1.8, 32, 32]}>
          <meshBasicMaterial color={primaryColor} transparent opacity={0.06} side={THREE.BackSide} />
        </Sphere>

        {/* “Head + body” placeholder: keep your existing procedural mesh if you want.
            This compact block is just a stable base that won’t break when you add GLB mode later. */}
        <group>
          <Sphere args={[0.75, 64, 64]} position={[0, 0.35, 0]}>
            <meshStandardMaterial
              color={HOLO_DARK}
              metalness={0.92}
              roughness={0.1}
              emissive={primaryColor}
              emissiveIntensity={0.03}
            />
          </Sphere>

          {/* Mouth “open” cue (simple) */}
          <Sphere args={[0.12, 16, 16]} position={[0, 0.18 - mouthOpen * 0.03, 0.58]}>
            <meshBasicMaterial color={HOLO_DARK} transparent opacity={0.2 + mouthOpen * 0.5} />
          </Sphere>

          {/* Eye blink glow indicator */}
          <Sphere args={[0.06, 16, 16]} position={[-0.18, 0.43, 0.58]} scale={[1, 1 - eyeBlink * 0.9, 1]}>
            <meshBasicMaterial color={primaryColor} transparent opacity={0.6 * (1 - squint)} />
          </Sphere>
          <Sphere args={[0.06, 16, 16]} position={[0.18, 0.43, 0.58]} scale={[1, 1 - eyeBlink * 0.9, 1]}>
            <meshBasicMaterial color={primaryColor} transparent opacity={0.6 * (1 - squint)} />
          </Sphere>

          {/* Body */}
          <Sphere args={[0.55, 64, 64]} position={[0, -0.55, 0]} scale={[1.05, 1.25, 0.85]}>
            <meshStandardMaterial
              color={HOLO_MID}
              metalness={0.9}
              roughness={0.12}
              emissive={primaryColor}
              emissiveIntensity={0.02}
            />
          </Sphere>
        </group>

        <HoloRing radius={1.05} speed={0.4} color={primaryColor} yPos={0.2} />
        <HoloRing radius={1.2} speed={-0.25} color={HOLO_SECONDARY} yPos={-0.5} />
        <HoloRing radius={0.9} speed={0.55} color={HOLO_ACCENT} yPos={-1.1} />

        <Sparkles count={80} scale={4} size={2} speed={0.4} color={primaryColor} opacity={0.5} />

        {speaking && (
          <Sparkles count={50} scale={2} size={3} speed={2} color={HOLO_GLOW} opacity={0.7} position={[0, -0.2, 0.8]} />
        )}
      </group>
    </Float>
  );
}

/* -----------------------------
   Gold-standard AvatarPanel fallback surface
   - This is no longer the primary runtime when a GLB/GLTF exists.
   - It remains a visual reference and emergency fallback card.
   - Production direction is true 3D mesh first, GoldStandard image second.
------------------------------ */
function GoldStandardAvatar({
  expression = "neutral",
  speaking = false,
  listening = false,
  thinking = false,
  gesture = "none",
  mouseTarget,
  idleUrl,
  focusedUrl,
  listeningUrl,
  happyUrl,
  overrideUrl,
  scale = 1.0,
  yOffset = -0.02,
  speechCues = [],
  speechStartTime = null,
}: {
  expression?: string;
  speaking?: boolean;
  listening?: boolean;
  thinking?: boolean;
  gesture?: AvatarSpec["gesture"];
  mouseTarget: { x: number; y: number };
  idleUrl?: string;
  focusedUrl?: string;
  listeningUrl?: string;
  happyUrl?: string;
  overrideUrl?: string;
  scale?: number;
  yOffset?: number;
  speechCues?: AvatarSpeechCue[];
  speechStartTime?: number | null;
}) {
  const groupRef = useRef<THREE.Group>(null);
  const bodyRef = useRef<THREE.Mesh>(null);
  const poseOverlayRef = useRef<THREE.Mesh>(null);
  const glowRef = useRef<THREE.Mesh>(null);
  const leftEyeBlinkRef = useRef<THREE.Mesh>(null);
  const rightEyeBlinkRef = useRef<THREE.Mesh>(null);
  const mouthRef = useRef<THREE.Mesh>(null);
  const hairLeftRef = useRef<THREE.Mesh>(null);
  const hairRightRef = useRef<THREE.Mesh>(null);
  const stageRef = useRef<THREE.Group>(null);

  const [blinkPhase, setBlinkPhase] = useState(0);

  const imageUrls = useMemo(() => {
    const idle = idleUrl || sarahGoldIdle;
    const focused = focusedUrl || sarahGoldFocused;
    const listen = listeningUrl || sarahGoldListening;
    const happy = happyUrl || sarahGoldHappy;
    const override = overrideUrl || "";
    return { idle, focused, listen, happy, override };
  }, [idleUrl, focusedUrl, listeningUrl, happyUrl, overrideUrl]);

  const textures = useMemo(() => {
    const loader = new THREE.TextureLoader();
    const build = (url: string) => {
      const tex = loader.load(url);
      tex.colorSpace = THREE.SRGBColorSpace;
      tex.anisotropy = 12;
      tex.generateMipmaps = true;
      tex.minFilter = THREE.LinearMipmapLinearFilter;
      tex.magFilter = THREE.LinearFilter;
      return tex;
    };
    return {
      idle: build(imageUrls.override || imageUrls.idle),
      focused: build(imageUrls.focused),
      listen: build(imageUrls.listen),
      happy: build(imageUrls.happy),
    };
  }, [imageUrls]);

  useEffect(() => {
    return () => {
      Object.values(textures).forEach((tex) => tex.dispose());
    };
  }, [textures]);

  const runtimePose = useMemo(() => {
    const e = String(expression || "").toLowerCase();
    if (gesture === "wave") return "wave";
    if (gesture === "walk") return "walk";
    if (speaking || listening) return "listening";
    if (e.includes("happy") || e.includes("joy") || e.includes("excited") || e.includes("success")) return "happy";
    if (thinking || e.includes("think") || e.includes("focus") || e.includes("diagnostic")) return "focused";
    return "idle";
  }, [expression, speaking, listening, thinking, gesture]);

  const baseTexture = useMemo(() => {
    if (runtimePose === "listening" || runtimePose === "wave") return textures.listen;
    if (runtimePose === "happy") return textures.happy;
    if (runtimePose === "focused") return textures.focused;
    return textures.idle;
  }, [runtimePose, textures]);

  const overlayTexture = useMemo(() => {
    if (runtimePose === "wave") return textures.happy;
    if (speaking || listening) return textures.listen;
    if (thinking) return textures.focused;
    return textures.idle;
  }, [runtimePose, speaking, listening, thinking, textures]);

  // Natural blink scheduler.  This is deliberately front-end only: visual life
  // inside the AvatarPanel without any physical robot control path.
  useEffect(() => {
    let closedTimer: number | undefined;
    let loopTimer: number | undefined;
    const schedule = () => {
      loopTimer = window.setTimeout(() => {
        setBlinkPhase(1);
        closedTimer = window.setTimeout(() => setBlinkPhase(0), 95 + Math.random() * 50);
        schedule();
      }, 2200 + Math.random() * 3200);
    };
    schedule();
    return () => {
      if (closedTimer) window.clearTimeout(closedTimer);
      if (loopTimer) window.clearTimeout(loopTimer);
    };
  }, []);

  useFrame(({ clock }) => {
    const t = clock.elapsedTime;
    const walking = runtimePose === "walk";
    const waving = runtimePose === "wave";

    let mouth = 0;
    if (speaking) {
      if (speechCues.length > 0 && speechStartTime) {
        const elapsed = Date.now() - speechStartTime;
        for (let i = 0; i < speechCues.length; i += 1) {
          if (speechCues[i].t <= elapsed) mouth = speechCues[i].v;
          else break;
        }
        mouth = clamp01(mouth);
      } else {
        mouth = 0.18 + Math.abs(Math.sin(t * 8.8)) * 0.62;
      }
    }

    if (groupRef.current) {
      const breathe = Math.sin(t * 1.12) * 0.010;
      const walkBob = walking ? Math.abs(Math.sin(t * 5.4)) * 0.045 : 0;
      const waveBob = waving ? Math.sin(t * 3.4) * 0.018 : 0;
      groupRef.current.position.y = yOffset + breathe + walkBob + waveBob;
      groupRef.current.rotation.y = THREE.MathUtils.lerp(groupRef.current.rotation.y, mouseTarget.x * 0.055 + Math.sin(t * 0.32) * 0.012, 0.06);
      groupRef.current.rotation.x = THREE.MathUtils.lerp(groupRef.current.rotation.x, mouseTarget.y * 0.020, 0.05);
    }

    if (bodyRef.current) {
      const pulse = speaking ? 1.0 + Math.sin(t * 7.2) * 0.007 : 1.0 + Math.sin(t * 1.15) * 0.004;
      const walkLean = walking ? Math.sin(t * 5.4) * 0.018 : 0;
      bodyRef.current.scale.set(scale * pulse * (walking ? 0.985 : 1.0), scale * pulse, scale * pulse);
      bodyRef.current.rotation.z = THREE.MathUtils.lerp(bodyRef.current.rotation.z, walkLean, 0.08);
    }

    if (poseOverlayRef.current) {
      const mat = poseOverlayRef.current.material as THREE.MeshBasicMaterial;
      const poseOpacity = waving ? 0.46 + Math.sin(t * 7.0) * 0.18 : (speaking || listening || thinking ? 0.18 + Math.sin(t * 2.0) * 0.06 : 0.0);
      mat.opacity = THREE.MathUtils.clamp(poseOpacity, 0, 0.62);
      poseOverlayRef.current.position.x = waving ? Math.sin(t * 7.0) * 0.018 : 0;
      poseOverlayRef.current.position.y = 0.085 + (waving ? Math.abs(Math.sin(t * 6.5)) * 0.012 : 0);
    }

    if (glowRef.current) {
      const mat = glowRef.current.material as THREE.MeshBasicMaterial;
      mat.opacity = 0.10 + Math.sin(t * 1.7) * 0.025 + (speaking ? 0.045 : 0) + (listening ? 0.035 : 0);
    }

    const blink = blinkPhase > 0 ? 0.78 : Math.max(0, Math.sin(t * 1.07) > 0.995 ? 0.65 : 0);
    for (const eye of [leftEyeBlinkRef.current, rightEyeBlinkRef.current]) {
      if (!eye) continue;
      const mat = eye.material as THREE.MeshBasicMaterial;
      mat.opacity = blink;
      eye.scale.y = 0.18 + blink * 0.82;
    }

    if (mouthRef.current) {
      mouthRef.current.scale.set(1.0 + mouth * 0.4, 0.25 + mouth * 1.25, 1.0);
      const mat = mouthRef.current.material as THREE.MeshBasicMaterial;
      mat.opacity = speaking ? 0.22 + mouth * 0.42 : 0.02;
    }

    const sway = Math.sin(t * 1.55) * 0.022 + mouseTarget.x * 0.012;
    if (hairLeftRef.current) {
      hairLeftRef.current.position.x = -0.30 + sway;
      hairLeftRef.current.rotation.z = -0.06 + sway * 1.6;
    }
    if (hairRightRef.current) {
      hairRightRef.current.position.x = 0.28 + sway * 0.7;
      hairRightRef.current.rotation.z = 0.04 + sway * 1.1;
    }

    if (stageRef.current) {
      stageRef.current.position.z = walking ? ((t * 0.18) % 0.35) - 0.175 : 0;
    }
  });

  return (
    <group ref={groupRef}>
      {/* Runtime stage: owned by AvatarPanel, lowered so it supports the character instead of cutting through the body. */}
      <group ref={stageRef} position={[0, -1.28, -0.34]} rotation={[0, 0, 0]}>
        <mesh rotation={[-Math.PI / 2, 0, 0]} receiveShadow>
          <planeGeometry args={[2.72, 1.52]} />
          <meshStandardMaterial color="#03070d" metalness={0.42} roughness={0.58} transparent opacity={0.86} />
        </mesh>
        <gridHelper args={[2.72, 8, "#28ddff", "#0b4c65"]} position={[0, 0.006, 0]} />
      </group>

      <mesh ref={glowRef} position={[0, -1.245, -0.12]} rotation={[-Math.PI / 2, 0, 0]}>
        <circleGeometry args={[0.58, 64]} />
        <meshBasicMaterial color="#29eaff" transparent opacity={0.10} depthWrite={false} blending={THREE.AdditiveBlending} />
      </mesh>

      {/* Photoreal local runtime card.  This remains the gold visual target while the GLB mesh matures. */}
      <mesh ref={bodyRef} position={[0, 0.08, 0.02]} renderOrder={20}>
        <planeGeometry args={[2.34, 2.34]} />
        <meshBasicMaterial map={baseTexture} transparent alphaTest={0.015} depthWrite={false} toneMapped={false} />
      </mesh>

      {/* Pose crossfade gives visible state/action changes without a full rigged high-poly model yet. */}
      <mesh ref={poseOverlayRef} position={[0, 0.085, 0.032]} renderOrder={22}>
        <planeGeometry args={[2.34, 2.34]} />
        <meshBasicMaterial map={overlayTexture} transparent opacity={0.0} alphaTest={0.015} depthWrite={false} toneMapped={false} blending={THREE.AdditiveBlending} />
      </mesh>

      {/* Visual life overlays: blinking, mouth motion, and hair sway.  These are AvatarPanel-only visual controls. */}
      <mesh ref={leftEyeBlinkRef} position={[-0.073, 0.775, 0.052]} renderOrder={30}>
        <planeGeometry args={[0.088, 0.018]} />
        <meshBasicMaterial color="#cf8f83" transparent opacity={0} depthWrite={false} toneMapped={false} />
      </mesh>
      <mesh ref={rightEyeBlinkRef} position={[0.071, 0.775, 0.052]} renderOrder={30}>
        <planeGeometry args={[0.088, 0.018]} />
        <meshBasicMaterial color="#cf8f83" transparent opacity={0} depthWrite={false} toneMapped={false} />
      </mesh>
      <mesh ref={mouthRef} position={[0.0, 0.645, 0.054]} renderOrder={31}>
        <circleGeometry args={[0.035, 24]} />
        <meshBasicMaterial color="#1b0710" transparent opacity={0.02} depthWrite={false} toneMapped={false} />
      </mesh>
      <mesh ref={hairLeftRef} position={[-0.30, 0.43, 0.046]} rotation={[0, 0, -0.06]} renderOrder={21}>
        <planeGeometry args={[0.055, 0.92]} />
        <meshBasicMaterial color="#ff3aa8" transparent opacity={0.10} depthWrite={false} toneMapped={false} blending={THREE.AdditiveBlending} />
      </mesh>
      <mesh ref={hairRightRef} position={[0.28, 0.44, 0.046]} rotation={[0, 0, 0.04]} renderOrder={21}>
        <planeGeometry args={[0.045, 0.76]} />
        <meshBasicMaterial color="#ff55bd" transparent opacity={0.08} depthWrite={false} toneMapped={false} blending={THREE.AdditiveBlending} />
      </mesh>

      <Sparkles count={speaking ? 84 : 48} scale={[2.4, 2.6, 0.6]} size={speaking ? 2.5 : 1.6} speed={speaking ? 1.45 : 0.45} color="#62f3ff" opacity={0.42} position={[0, -0.05, -0.15]} />
    </group>
  );
}

/* -----------------------------
   GLTF Avatar (backend-generated)
------------------------------ */
function GltfAvatar({
  url,
  lookAt,
  speaking = false,
  listening = false,
  thinking = false,
  expression = "neutral",
  pose = "stand",
  gesture = "none",
  bodyProfile,
  avatarOffsetY = -0.08,
  stageOffsetY = -0.08,
  useRuntimeStage = true,
  materialMode = "high_end",
  mouseTarget = { x: 0, y: 0 },
}: {
  url: string;
  lookAt?: { x: number; y: number; z: number };
  speaking?: boolean;
  listening?: boolean;
  thinking?: boolean;
  expression?: string;
  pose?: AvatarPose;
  gesture?: AvatarSpec["gesture"];
  bodyProfile?: AvatarSpec["bodyProfile"];
  avatarOffsetY?: number;
  stageOffsetY?: number;
  useRuntimeStage?: boolean;
  materialMode?: "balanced" | "high_end";
  mouseTarget?: { x: number; y: number };
}) {
  const groupRef = useRef<THREE.Group>(null);
  const gltf = useGLTF(url, true);

  const prepared = useMemo(() => {
    const cloned = SkeletonUtils.clone(gltf.scene) as THREE.Group;
    const morphMeshes: THREE.Mesh[] = [];
    const bones: Record<string, THREE.Object3D> = {};
    const stageScene = new THREE.Group();
    stageScene.name = "Sarah_RuntimeStage";
    const stageObjects: THREE.Object3D[] = [];
    const semanticObjects = {
      hair: [] as THREE.Object3D[],
      eyes: [] as THREE.Object3D[],
      iris: [] as THREE.Object3D[],
      head: [] as THREE.Object3D[],
      neon: [] as THREE.Object3D[],
    };

    cloned.traverse((obj) => {
      const anyObj = obj as any;
      if (obj.type === "Bone" || /^(root|pelvis|spine|neck|head|jaw|eye|clavicle|upper_arm|forearm|hand|thigh|shin|foot|toe)/i.test(obj.name)) {
        bones[obj.name] = obj;
        bones[obj.name.toLowerCase()] = obj;
      }

      if (anyObj.isMesh || anyObj.isSkinnedMesh) {
        const mesh = obj as THREE.Mesh;
        mesh.castShadow = !isSarahStageObject(mesh.name);
        mesh.receiveShadow = true;
        mesh.frustumCulled = false;
        if ((mesh as any).morphTargetDictionary && (mesh as any).morphTargetInfluences) {
          morphMeshes.push(mesh);
        }
        enhanceSarahMaterial(mesh, materialMode);
        const meshKey = String(mesh.name || "").toLowerCase();
        if (/hair/.test(meshKey)) semanticObjects.hair.push(mesh);
        if (/eye|sclera/.test(meshKey)) semanticObjects.eyes.push(mesh);
        if (/iris/.test(meshKey)) semanticObjects.iris.push(mesh);
        if (/head|face|lip|brow|lash|mouth|tooth/.test(meshKey)) semanticObjects.head.push(mesh);
        if (/neon|circuit|trim|glow/.test(meshKey)) semanticObjects.neon.push(mesh);
        if (isSarahStageObject(mesh.name)) {
          stageObjects.push(mesh);
        }
      }
    });

    for (const obj of stageObjects) {
      if (obj.parent) {
        obj.parent.remove(obj);
        stageScene.add(obj);
      }
    }

    // Do not auto-play Blender-exported clips.  Sarah's modular runtime parts
    // include skinned meshes plus non-skinned neon/hair/facial detail geometry.
    // Auto-playing a generic demo clip moves only the skinned body, making the
    // suit/trim/hair appear like a second floating avatar.  Future authored
    // animation clips must be explicitly selected by the Avatar Organ contract.
    const mixer = gltf.animations && gltf.animations.length > 0 ? new THREE.AnimationMixer(cloned) : null;
    const clipsByName = new Map<string, THREE.AnimationClip>();
    (gltf.animations || []).forEach((clip) => clipsByName.set(String(clip.name || "").toLowerCase(), clip));

    return { scene: cloned, stageScene, morphMeshes, bones, mixer, clipsByName, semanticObjects };
  }, [gltf.scene, gltf.animations, materialMode]);

  const fit = useMemo(() => {
    const box = new THREE.Box3().setFromObject(prepared.scene);
    const size = new THREE.Vector3();
    const center = new THREE.Vector3();
    box.getSize(size);
    box.getCenter(center);

    // Ground the avatar by its lowest exported point, not by vertical center.
    // Centering by Y made the AvatarPanel floor/stage and body read as two
    // separated layers on some builds.  This keeps boots/stage visually locked.
    const height = Math.max(size.y || 1, 0.1);
    const heightTarget = bodyProfile?.height_m && bodyProfile.height_m > 0 ? bodyProfile.height_m : 1.68;
    const baseScale = height > 0 ? Math.min(1.78, 3.05 / height) : 1;
    const humanScaleCorrection = THREE.MathUtils.clamp(1.68 / heightTarget, 0.88, 1.14);
    const bottomY = Number.isFinite(box.min.y) ? box.min.y : 0;

    return { center, bottomY, scale: baseScale * humanScaleCorrection };
  }, [prepared.scene, bodyProfile?.height_m]);

  const setMorph = useCallback(
    (name: string, value: number) => {
      const v = THREE.MathUtils.clamp(value, 0, 1);
      const aliases = [name, name.toLowerCase(), name.replace("_", "."), name.replace("_", ""), name.replace(".", "_")];
      for (const mesh of prepared.morphMeshes) {
        const dict = (mesh as any).morphTargetDictionary as Record<string, number> | undefined;
        const influences = (mesh as any).morphTargetInfluences as number[] | undefined;
        if (!dict || !influences) continue;
        let index: number | undefined;
        for (const key of aliases) {
          if (typeof dict[key] === "number") {
            index = dict[key];
            break;
          }
        }
        if (typeof index === "number") {
          influences[index] = THREE.MathUtils.lerp(influences[index] ?? 0, v, 0.38);
        }
      }
    },
    [prepared.morphMeshes]
  );

  const setMorphAny = useCallback(
    (names: string[], value: number) => {
      for (const n of names) setMorph(n, value);
    },
    [setMorph]
  );

  const bone = useCallback((...names: string[]) => {
    for (const name of names) {
      const found = prepared.bones[name] || prepared.bones[name.toLowerCase()];
      if (found) return found;
    }
    return null;
  }, [prepared.bones]);

  useFrame((state, delta) => {
    const t = state.clock.elapsedTime;
    // Mixer intentionally remains idle unless a future explicit clip contract enables it.
    // prepared.mixer?.update(delta);

    const walking = pose === "walk" || gesture === "walk";
    const turningLeft = pose === "turn_left" || gesture === "turn_left";
    const turningRight = pose === "turn_right" || gesture === "turn_right";
    const waving = pose === "wave" || gesture === "wave";

    if (groupRef.current) {
      const idleBreath = Math.sin(t * 0.9) * 0.018 + Math.sin(t * 1.8 + 0.6) * 0.004;
      const speakingPulse = speaking ? Math.sin(t * 9.5) * 0.012 : 0;
      const walkBounce = walking ? Math.abs(Math.sin(t * 5.2)) * 0.035 : 0;
      groupRef.current.position.y = avatarOffsetY + idleBreath + speakingPulse + walkBounce + (pose === "sit" ? -0.28 : 0);

      const targetYaw = lookAt ? THREE.MathUtils.clamp(lookAt.x * 0.04, -0.12, 0.12) : 0;
      const idleYaw = Math.sin(t * 0.35) * 0.035;
      const turnYaw = turningLeft ? -0.34 : turningRight ? 0.34 : 0;
      const idleRoll = Math.sin(t * 0.48 + 0.4) * 0.012;
      const idlePitch = Math.sin(t * 0.62 + 1.3) * 0.010;
      groupRef.current.rotation.y = THREE.MathUtils.lerp(groupRef.current.rotation.y, targetYaw + idleYaw + turnYaw, 0.045);
      groupRef.current.rotation.z = THREE.MathUtils.lerp(groupRef.current.rotation.z, idleRoll, 0.04);
      groupRef.current.rotation.x = THREE.MathUtils.lerp(groupRef.current.rotation.x, idlePitch, 0.04);
    }

    // Face: more natural blink cadence, jaw cadence, subtle asymmetry, and calmer idle life.
    const blinkCarrierA = Math.sin(t * 0.73) * 0.5 + 0.5;
    const blinkCarrierB = Math.sin(t * 1.91 + 1.37) * 0.5 + 0.5;
    const blinkTrigger = blinkCarrierA * 0.62 + blinkCarrierB * 0.38;
    const blinkPulse = Math.pow(THREE.MathUtils.clamp((blinkTrigger - 0.90) / 0.10, 0, 1), 1.8);
    const blinkLeft = THREE.MathUtils.clamp(blinkPulse * (0.96 + Math.sin(t * 2.6) * 0.035), 0, 1);
    const blinkRight = THREE.MathUtils.clamp(blinkPulse * (1.02 + Math.cos(t * 2.2 + 0.7) * 0.03), 0, 1);
    const jawIdle = speaking ? 0.14 : 0.0;
    const jawSpeech = speaking ? (0.08 + Math.abs(Math.sin(t * 8.4)) * 0.36 + Math.abs(Math.sin(t * 4.7 + 0.4)) * 0.14) : 0.0;
    const jaw = THREE.MathUtils.clamp(jawIdle + jawSpeech, 0, 0.72);
    const smile = /happy|joy|success|trust|hello|approval|soft|friendly/i.test(expression) ? 0.72 : speaking ? 0.14 : 0.05;
    const frown = /sad|worried|concerned|frustrated|angry|anger/i.test(expression) ? 0.58 : 0;
    const brows = listening || thinking || /thinking|pondering|wondering|surprise/i.test(expression) ? 0.42 : 0.07;
    setMorphAny(["Blink_L", "blinkLeft", "Blink.Left"], blinkLeft);
    setMorphAny(["Blink_R", "blinkRight", "Blink.Right"], blinkRight);
    setMorphAny(["BlinkBoth", "Blink", "EyesClosed"], Math.min(blinkLeft, blinkRight) * 0.35);
    setMorphAny(["JawOpen", "jawOpen", "MouthOpen"], jaw);
    setMorphAny(["Smile", "MouthSmile"], smile);
    setMorphAny(["Frown", "MouthFrown"], frown);
    setMorphAny(["BrowsUp", "BrowRaise"], brows);
    setMorphAny(["Squint_L", "Squint_R"], thinking ? 0.12 : 0.0);
    setMorphAny(["MouthWide"], speaking ? 0.10 + Math.abs(Math.sin(t * 6.2)) * 0.16 : 0.0);

    // v9.0.12: governed visual motion is enabled for the true GLB runtime.
    // The Blender patch binds neon, facial, and hair detail layers to Sarah_Rig
    // with explicit vertex groups, so small skeletal motion no longer tears the
    // suit lines or hair away from the body.  This remains AvatarPanel visual
    // motion only; it does not authorize MSDC or physical robot movement.
    const head = bone("head");
    const neck = bone("neck");
    const spine01 = bone("spine.01", "spine_01");
    const spine02 = bone("spine.02", "spine_02");
    const spine03 = bone("spine.03", "spine_03");
    const eyeL = bone("eye.L", "eye_l", "eye.left");
    const eyeR = bone("eye.R", "eye_r", "eye.right");
    const hairRoot = bone("hair_root", "hair.root");
    const hair01 = bone("hair.01", "hair_01");
    const hair02 = bone("hair.02", "hair_02");
    const hair03 = bone("hair.03", "hair_03");
    const upperArmL = bone("upper_arm.L", "upper_arm_l");
    const upperArmR = bone("upper_arm.R", "upper_arm_r");
    const forearmL = bone("forearm.L", "forearm_l");
    const forearmR = bone("forearm.R", "forearm_r");
    const thighL = bone("thigh.L", "thigh_l");
    const thighR = bone("thigh.R", "thigh_r");
    const shinL = bone("shin.L", "shin_l");
    const shinR = bone("shin.R", "shin_r");

    const saccadeX = Math.sin(t * 0.83) * 0.008 + Math.sin(t * 2.63 + 1.1) * 0.004;
    const saccadeY = Math.cos(t * 0.67 + 0.3) * 0.006 + Math.sin(t * 1.91 + 0.9) * 0.003;
    const lookX = (lookAt ? THREE.MathUtils.clamp(lookAt.x * 0.08, -0.18, 0.18) : THREE.MathUtils.clamp(mouseTarget.x * 0.12, -0.16, 0.16)) + saccadeX;
    const lookY = (lookAt ? THREE.MathUtils.clamp((lookAt.y - 1.45) * 0.08, -0.10, 0.10) : THREE.MathUtils.clamp(mouseTarget.y * 0.06, -0.08, 0.08)) + saccadeY;
    const focusBoost = listening || thinking ? 0.035 : 0.0;

    if (head) {
      head.rotation.y = THREE.MathUtils.lerp(head.rotation.y, lookX + Math.sin(t * 0.42) * 0.018, 0.08);
      head.rotation.x = THREE.MathUtils.lerp(head.rotation.x, -lookY + focusBoost, 0.08);
    }
    if (neck) {
      neck.rotation.y = THREE.MathUtils.lerp(neck.rotation.y, lookX * 0.36, 0.07);
      neck.rotation.x = THREE.MathUtils.lerp(neck.rotation.x, -lookY * 0.32, 0.07);
    }
    if (spine01) spine01.rotation.x = THREE.MathUtils.lerp(spine01.rotation.x, Math.sin(t * 1.08) * 0.010, 0.06);
    if (spine02) spine02.rotation.z = THREE.MathUtils.lerp(spine02.rotation.z, Math.sin(t * 0.72) * 0.008, 0.06);
    if (spine03) spine03.rotation.y = THREE.MathUtils.lerp(spine03.rotation.y, lookX * 0.18, 0.05);

    for (const eye of [eyeL, eyeR]) {
      if (!eye) continue;
      eye.rotation.y = THREE.MathUtils.lerp(eye.rotation.y, lookX * 1.8, 0.18);
      eye.rotation.x = THREE.MathUtils.lerp(eye.rotation.x, -lookY * 1.4, 0.18);
    }

    const torsoSway = Math.sin(t * 0.58) * 0.022 + Math.sin(t * 1.22 + 0.8) * 0.010;
    const hairSway = Math.sin(t * 1.05) * 0.030 + Math.sin(t * 1.92 + 0.5) * 0.015 + torsoSway * 0.7 + lookX * 0.18;
    const hairLift = Math.sin(t * 0.92 + 0.2) * 0.020 + (walking ? Math.sin(t * 5.2) * 0.010 : 0);
    if (hairRoot) {
      hairRoot.rotation.z = THREE.MathUtils.lerp(hairRoot.rotation.z, hairSway * 0.20, 0.045);
      hairRoot.rotation.x = THREE.MathUtils.lerp(hairRoot.rotation.x, hairLift * 0.12, 0.04);
      hairRoot.rotation.y = THREE.MathUtils.lerp(hairRoot.rotation.y, lookX * 0.08, 0.04);
    }
    if (hair01) {
      hair01.rotation.z = THREE.MathUtils.lerp(hair01.rotation.z, hairSway * 0.40, 0.05);
      hair01.rotation.x = THREE.MathUtils.lerp(hair01.rotation.x, hairLift * 0.18, 0.045);
    }
    if (hair02) {
      hair02.rotation.z = THREE.MathUtils.lerp(hair02.rotation.z, hairSway * 0.68, 0.055);
      hair02.rotation.x = THREE.MathUtils.lerp(hair02.rotation.x, hairLift * 0.24, 0.05);
    }
    if (hair03) {
      hair03.rotation.z = THREE.MathUtils.lerp(hair03.rotation.z, hairSway * 0.96, 0.06);
      hair03.rotation.x = THREE.MathUtils.lerp(hair03.rotation.x, hairLift * 0.30, 0.055);
    }

    prepared.semanticObjects.hair.forEach((obj, idx) => {
      const phase = idx * 0.37;
      obj.rotation.z = THREE.MathUtils.lerp(obj.rotation.z, Math.sin(t * 1.05 + phase) * 0.012 + Math.sin(t * 2.1 + phase) * 0.006 + lookX * 0.014, 0.025);
      obj.rotation.x = THREE.MathUtils.lerp(obj.rotation.x, Math.cos(t * 0.88 + phase) * 0.005 + hairLift * 0.08, 0.02);
    });
    prepared.semanticObjects.iris.forEach((obj) => {
      obj.rotation.y = THREE.MathUtils.lerp(obj.rotation.y, lookX * 0.55, 0.16);
      obj.rotation.x = THREE.MathUtils.lerp(obj.rotation.x, -lookY * 0.42, 0.16);
    });

    if (waving) {
      if (upperArmR) upperArmR.rotation.z = THREE.MathUtils.lerp(upperArmR.rotation.z, -0.82, 0.09);
      if (forearmR) forearmR.rotation.z = THREE.MathUtils.lerp(forearmR.rotation.z, -0.55 + Math.sin(t * 7.0) * 0.24, 0.12);
    } else {
      if (upperArmR) upperArmR.rotation.z = THREE.MathUtils.lerp(upperArmR.rotation.z, Math.sin(t * 0.55) * 0.010 - torsoSway * 0.18, 0.04);
      if (forearmR) forearmR.rotation.z = THREE.MathUtils.lerp(forearmR.rotation.z, 0, 0.05);
    }
    if (upperArmL) upperArmL.rotation.z = THREE.MathUtils.lerp(upperArmL.rotation.z, Math.sin(t * 0.50 + 0.8) * 0.010 + torsoSway * 0.18, 0.04);
    if (forearmL) forearmL.rotation.z = THREE.MathUtils.lerp(forearmL.rotation.z, 0, 0.05);

    if (walking) {
      const walk = Math.sin(t * 5.4);
      if (thighL) thighL.rotation.x = THREE.MathUtils.lerp(thighL.rotation.x, walk * 0.20, 0.10);
      if (thighR) thighR.rotation.x = THREE.MathUtils.lerp(thighR.rotation.x, -walk * 0.20, 0.10);
      if (shinL) shinL.rotation.x = THREE.MathUtils.lerp(shinL.rotation.x, Math.max(0, -walk) * 0.18, 0.10);
      if (shinR) shinR.rotation.x = THREE.MathUtils.lerp(shinR.rotation.x, Math.max(0, walk) * 0.18, 0.10);
    } else {
      for (const legBone of [thighL, thighR, shinL, shinR]) {
        if (legBone) legBone.rotation.x = THREE.MathUtils.lerp(legBone.rotation.x, 0, 0.05);
      }
    }
  });

  return (
    <>
      {useRuntimeStage && prepared.stageScene.children.length > 0 && (
        <group position={[0, stageOffsetY, 0]} scale={fit.scale}>
          <primitive object={prepared.stageScene} position={[-fit.center.x, -fit.bottomY, -fit.center.z]} />
        </group>
      )}
      <group ref={groupRef} position={[0, avatarOffsetY, 0]} scale={fit.scale}>
        <primitive object={prepared.scene} position={[-fit.center.x, -fit.bottomY, -fit.center.z]} />
      </group>
    </>
  );
}

/* -----------------------------
   Video “Hologram Sprite”
   - useful while backend generates real rigs/models
------------------------------ */
function VideoSpriteAvatar({ url }: { url: string }) {
  const meshRef = useRef<THREE.Mesh>(null);

  const texture = useMemo(() => {
    const video = document.createElement("video");
    video.src = url;
    video.muted = true;
    video.loop = true;
    video.playsInline = true;
    video.autoplay = true;
    video.crossOrigin = "anonymous";
    video.play().catch(() => {});
    const tex = new THREE.VideoTexture(video);
    tex.colorSpace = THREE.SRGBColorSpace;
    return tex;
  }, [url]);

  useFrame(({ camera }) => {
    if (!meshRef.current) return;
    // billboard toward camera
    meshRef.current.quaternion.copy(camera.quaternion);
  });

  return (
    <mesh ref={meshRef} position={[0, -0.6, 0]}>
      <planeGeometry args={[2.1, 3.2]} />
      <meshBasicMaterial map={texture} transparent opacity={0.95} />
    </mesh>
  );
}

/* -----------------------------
   Camera Controller
------------------------------ */
function CameraController() {
  const { camera } = useThree();
  useEffect(() => {
    camera.position.set(0, 0.3, 4.0);
    camera.lookAt(0, -0.05, 0);
  }, [camera]);
  return null;
}

export function Avatar3D({ speaking = false, listening = false, expression = "neutral", spec }: Avatar3DProps) {
  const { avatarSpeaking, speechCues, speechStartTime, avatarPose, setAvatarPose, triggerWave } = useSarahStore();

  const [mouseTarget, setMouseTarget] = useState({ x: 0, y: 0 });
  const [meshInspectMode, setMeshInspectMode] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  // Unified “effective” state (props < store < spec)
  const effective = useMemo(() => {
    const effSpeaking = spec?.speaking ?? (avatarSpeaking || speaking);
    const effListening = spec?.listening ?? listening;
    const effExpression = spec?.expression ?? expression;

    return {
      renderMode: spec?.renderMode ?? ((spec?.modelUrl || spec?.meshFallbackUrl) ? "gltf_model" : "gold_standard_avatar"),
      modelUrl: spec?.modelUrl,
      videoUrl: spec?.videoUrl,
      backgroundUrl: spec?.backgroundUrl,
      backgroundType: spec?.backgroundType ?? "none",
      goldStandardUrl: spec?.goldStandardUrl,
      goldStandardIdleUrl: spec?.goldStandardIdleUrl,
      goldStandardFocusedUrl: spec?.goldStandardFocusedUrl,
      goldStandardListeningUrl: spec?.goldStandardListeningUrl,
      goldStandardHappyUrl: spec?.goldStandardHappyUrl,
      goldStandardScale: spec?.goldStandardScale ?? 1.0,
      goldStandardYOffset: spec?.goldStandardYOffset ?? -0.02,
      meshFallbackUrl: spec?.meshFallbackUrl,
      runtimeVisualPriority: spec?.runtimeVisualPriority ?? ((spec?.modelUrl || spec?.meshFallbackUrl) ? "gltf_model" : "gold_standard"),
      forceMeshRuntime: spec?.forceMeshRuntime ?? Boolean(spec?.modelUrl || spec?.meshFallbackUrl),
      goldReferenceOnly: spec?.goldReferenceOnly ?? Boolean(spec?.modelUrl || spec?.meshFallbackUrl),
      authoringPolyTarget: spec?.authoringPolyTarget ?? 12000000,
      runtimeLod: spec?.runtimeLod ?? "goldstandard_entity",
      productionAssetContract: spec?.productionAssetContract ?? "SARAHMEMORY_TRUE_3D_PRODUCTION_ASSET_V1",
      blueprintConstructReady: spec?.blueprintConstructReady ?? true,
      visualEffectsMode: spec?.visualEffectsMode ?? "secondary",
      pose: spec?.pose ?? avatarPose,
      gesture: spec?.gesture ?? "none",
      lookAt: spec?.lookAt,
      speaking: effSpeaking,
      listening: effListening,
      thinking: spec?.thinking ?? false,
      expression: effExpression,
      bodyProfile: spec?.bodyProfile,
      loaderState: spec?.loaderState,
      quality: spec?.quality ?? "goldstandard_entity",
      fpsCap: spec?.fpsCap ?? 60,
      lightingProfile: spec?.lightingProfile ?? "high_end",
      shadowQuality: spec?.shadowQuality ?? "high",
      stageOffsetY: spec?.stageOffsetY ?? -0.08,
      avatarOffsetY: spec?.avatarOffsetY ?? -0.08,
      useRuntimeStage: spec?.useRuntimeStage ?? true,
      materialMode: spec?.materialMode ?? "high_end",
      speechCues: spec?.speechCues ?? speechCues,
      speechStartTime: spec?.speechStartTime ?? speechStartTime,
    };
  }, [spec, avatarSpeaking, speaking, listening, expression, speechCues, speechStartTime, avatarPose]);

  // Mouse-follow
  const handleMouseMove = useCallback((e: React.MouseEvent<HTMLDivElement>) => {
    if (!containerRef.current) return;
    const rect = containerRef.current.getBoundingClientRect();
    const x = ((e.clientX - rect.left) / rect.width - 0.5) * 2;
    const y = ((e.clientY - rect.top) / rect.height - 0.5) * -2;
    setMouseTarget({ x, y });
  }, []);

  const handleMouseLeave = useCallback(() => setMouseTarget({ x: 0, y: 0 }), []);

  // Keyboard shortcuts (keep your existing)
  useEffect(() => {
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;
      switch (e.key.toLowerCase()) {
        case "w":
          triggerWave();
          break;
        case "s":
          setAvatarPose("sit");
          break;
        case "d":
          setAvatarPose("stand");
          break;
        case "m":
          setMeshInspectMode((v) => !v);
          break;
        case "g":
          setMeshInspectMode(false);
          break;
      }
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [setAvatarPose, triggerWave]);

  const activeModelUrl = effective.modelUrl || effective.meshFallbackUrl || "";

  // Production rule: if a GLB/GLTF exists, render the true mesh first.
  // GoldStandard images are visual references/fallback only and must not mask a
  // weak 3D build.  This keeps defects visible so the asset forge can improve.
  const safeRenderMode: AvatarRenderMode = useMemo(() => {
    if (activeModelUrl && (effective.forceMeshRuntime || effective.runtimeVisualPriority === "gltf_model" || effective.renderMode === "gltf_model" || meshInspectMode)) return "gltf_model";
    if (effective.renderMode === "gltf_model" && !activeModelUrl) return "gold_standard_avatar";
    if (effective.renderMode === "video_sprite" && !effective.videoUrl) return "procedural_holo";
    return effective.renderMode;
  }, [meshInspectMode, effective.forceMeshRuntime, effective.runtimeVisualPriority, effective.renderMode, effective.videoUrl, activeModelUrl]);

  const toggleMeshInspect = useCallback(() => {
    if (!activeModelUrl) return;
    setMeshInspectMode((v) => !v);
  }, [activeModelUrl]);

  const cinematicViewport = isCinematicQuality(effective.quality);
  const highViewport = isHighOrBetterQuality(effective.quality);
  const shadowMapSize = qualityShadowSize(effective.quality);

  return (
    <div
      ref={containerRef}
      className="relative h-full w-full"
      onMouseMove={handleMouseMove}
      onMouseLeave={handleMouseLeave}
      onDoubleClick={toggleMeshInspect}
      onContextMenu={(e) => {
        e.preventDefault();
        toggleMeshInspect();
      }}
      title="SarahMemory True 3D Avatar Runtime. GoldStandard is reference/fallback only."
    >
      <Canvas
        shadows={effective.shadowQuality !== "off"}
        camera={{ position: [0, 0.72, 2.65], fov: safeRenderMode === "gltf_model" ? (cinematicViewport ? 22 : 28) : 34 }}
        dpr={qualityDpr(effective.quality)}
        gl={{ antialias: effective.quality !== "preview", alpha: true, powerPreference: "high-performance", precision: "highp" }}
        onCreated={({ gl }) => {
          gl.outputColorSpace = THREE.SRGBColorSpace;
          gl.toneMapping = THREE.ACESFilmicToneMapping;
          gl.toneMappingExposure = qualityToneExposure(effective.quality);
          gl.shadowMap.enabled = effective.shadowQuality !== "off";
          gl.shadowMap.type = THREE.PCFSoftShadowMap;
          gl.setPixelRatio(Math.min(window.devicePixelRatio || 1, isCinematicQuality(effective.quality) ? 3.5 : isHighOrBetterQuality(effective.quality) ? 2.75 : 2.0));
        }}
        performance={{ min: cinematicViewport ? 0.75 : 0.5 }}
        style={{ background: "transparent" }}
      >
        <CameraController />

        {/* Background plane (optional) */}
        <SceneBackground url={effective.backgroundUrl} type={effective.backgroundType} />

        {/* High-end local production lighting rig.  Body/skin/suit readability takes priority over VFX glow. */}
        <hemisphereLight args={["#f7fcff", "#04060a", cinematicViewport ? 1.58 : highViewport ? 1.42 : 1.18]} />
        <ambientLight intensity={cinematicViewport ? 1.06 : highViewport ? 0.96 : 0.72} color="#dffbff" />
        <directionalLight
          castShadow
          position={[1.15, 3.6, 4.8]}
          intensity={cinematicViewport ? 3.65 : highViewport ? 3.1 : 2.3}
          color="#ffffff"
          shadow-mapSize-width={shadowMapSize}
          shadow-mapSize-height={shadowMapSize}
          shadow-camera-near={0.5}
          shadow-camera-far={12}
          shadow-camera-left={-3.5}
          shadow-camera-right={3.5}
          shadow-camera-top={3.5}
          shadow-camera-bottom={-3.5}
          shadow-bias={-0.00012}
        />
        <pointLight position={[2.8, 2.2, 2.6]} intensity={safeRenderMode === "gltf_model" ? (cinematicViewport ? 1.32 : 1.05) : 1.45} color="#63f3ff" />
        <pointLight position={[-2.6, 1.8, 1.5]} intensity={safeRenderMode === "gltf_model" ? (cinematicViewport ? 0.72 : 0.58) : 0.9} color="#2dd0ff" />
        <pointLight position={[0, 0.55, 2.55]} intensity={safeRenderMode === "gltf_model" ? (cinematicViewport ? 1.15 : 0.92) : 0.65} color="#ffffff" />

        {/* Avatar */}
        {safeRenderMode === "gold_standard_avatar" ? (
          <GoldStandardAvatar
            expression={effective.expression}
            speaking={effective.speaking}
            listening={effective.listening}
            thinking={effective.thinking}
            gesture={effective.gesture}
            mouseTarget={mouseTarget}
            idleUrl={effective.goldStandardIdleUrl}
            focusedUrl={effective.goldStandardFocusedUrl}
            listeningUrl={effective.goldStandardListeningUrl}
            happyUrl={effective.goldStandardHappyUrl}
            overrideUrl={effective.goldStandardUrl}
            scale={effective.goldStandardScale}
            yOffset={effective.goldStandardYOffset}
            speechCues={effective.speechCues}
            speechStartTime={effective.speechStartTime}
          />
        ) : safeRenderMode === "gltf_model" && activeModelUrl ? (
          <React.Suspense
            fallback={
              <Html center>
                <div className="text-xs text-muted-foreground">Loading SarahMemory 3D Avatar Organ…</div>
              </Html>
            }
          >
            <GltfAvatar
              url={activeModelUrl}
              lookAt={effective.lookAt}
              speaking={effective.speaking}
              listening={effective.listening}
              thinking={effective.thinking}
              expression={effective.expression}
              pose={effective.pose}
              gesture={effective.gesture}
              bodyProfile={effective.bodyProfile}
              avatarOffsetY={effective.avatarOffsetY}
              stageOffsetY={effective.stageOffsetY}
              useRuntimeStage={effective.useRuntimeStage}
              materialMode={effective.materialMode === "balanced" ? "balanced" : "high_end"}
              mouseTarget={mouseTarget}
            />
          </React.Suspense>
        ) : safeRenderMode === "video_sprite" && effective.videoUrl ? (
          <VideoSpriteAvatar url={effective.videoUrl} />
        ) : (
          <ProceduralHoloAvatar
            expression={effective.expression}
            speaking={effective.speaking}
            listening={effective.listening}
            speechCues={effective.speechCues}
            speechStartTime={effective.speechStartTime}
            pose={effective.pose}
            gesture={effective.gesture}
            mouseTarget={mouseTarget}
          />
        )}

        {effective.shadowQuality !== "off" && (
          <ContactShadows
            position={[0, (effective.avatarOffsetY ?? -1.16) + 0.02, 0]}
            opacity={cinematicViewport ? 0.66 : highViewport ? 0.56 : 0.38}
            scale={3.6}
            blur={2.2}
            far={3.8}
            resolution={cinematicViewport ? 4096 : highViewport ? 2048 : 512}
            color="#0b1018"
          />
        )}

        {/* True orbit/zoom is active in mesh-inspect mode.  Gold mode keeps subtle parallax so it does not expose a flat card when dragged. */}
        <OrbitControls
          enablePan={safeRenderMode === "gltf_model"}
          enableZoom={true}
          minDistance={safeRenderMode === "gltf_model" ? 1.4 : 2.45}
          maxDistance={8}
          enableRotate={safeRenderMode === "gltf_model"}
          enableDamping={true}
          dampingFactor={0.08}
          target={[0, safeRenderMode === "gltf_model" ? 0.48 : -0.22, 0]}
        />
      </Canvas>

      <div className="pointer-events-none absolute right-3 bottom-3 z-20 rounded-md border border-cyan-500/25 bg-slate-950/70 px-2 py-1 text-[10px] uppercase tracking-[0.18em] text-cyan-100/75 shadow-[0_0_18px_rgba(0,212,255,0.18)] backdrop-blur-sm">
        {safeRenderMode === "gltf_model" ? cinematicViewport ? "GoldStandard Embodied GLB · Gold Ref Only" : "True 3D Mesh · Gold Ref Only" : "Gold Fallback · No GLB Loaded"}
      </div>
    </div>
  );
}

// Allow GLTF caching
useGLTF.preload("/api/avatar/3d/SarahMemoryAvatar_RigBootstrap.glb");
