# Auto-generated by SM-AVATARBUILD.py. Local-only deterministic 3D avatar build.
import os
import math
import json
import bpy
from mathutils import Vector

CFG = json.loads(r"""{
  "builder": "SM-AVATARBUILD.py",
  "mode": "build_3d_avatar",
  "concept_image": "S:\\SarahMemory\\SarahMemory_3D.png",
  "outdir": "S:\\SarahMemory\\resources\\avatars\\3D",
  "glb_path": "S:\\SarahMemory\\resources\\avatars\\3D\\sarahmemory_3d_avatar.glb",
  "blend_path": "S:\\SarahMemory\\resources\\avatars\\3D\\sarahmemory_3d_avatar.blend",
  "preview_path": "S:\\SarahMemory\\resources\\avatars\\3D\\sarahmemory_3d_avatar_preview.png",
  "render_preview": true,
  "gpu_backend": "OPTIX",
  "poly_target": 90000,
  "palette": {
    "source_image": "S:\\SarahMemory\\SarahMemory_3D.png",
    "source_exists": true,
    "palette_source": "concept_image_sampled",
    "image_size": [
      1055,
      1491
    ],
    "hair": [
      0.6521297788521802,
      0.3434215238606858,
      0.39552780016116035
    ],
    "suit": [
      0.07570793855581986,
      0.11556516012847909,
      0.1415934093994006
    ],
    "glow": [
      0.26358273621063155,
      0.5698905737932567,
      0.6638065877909237
    ],
    "skin": [
      0.7980950375920662,
      0.6970535603211514,
      0.6735924107726708
    ],
    "boot": [
      0.05792094615624027,
      0.1068519715578539,
      0.1395700160406043
    ]
  }
}""")


def _color(name, default):
    val = CFG.get("palette", {}).get(name, default)
    if isinstance(val, (list, tuple)) and len(val) >= 3:
        return (float(val[0]), float(val[1]), float(val[2]), 1.0)
    return (float(default[0]), float(default[1]), float(default[2]), 1.0)


def clear_scene():
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete()


def set_socket(node, socket_names, value):
    if node is None:
        return
    for s in socket_names:
        if s in node.inputs:
            try:
                node.inputs[s].default_value = value
                return
            except Exception:
                pass


def make_mat(name, base=(1,1,1,1), metallic=0.0, roughness=0.45, emission=None, emission_strength=0.0, alpha=1.0):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get('Principled BSDF')
    if bsdf:
        set_socket(bsdf, ('Base Color',), base)
        set_socket(bsdf, ('Metallic',), float(metallic))
        set_socket(bsdf, ('Roughness',), float(roughness))
        set_socket(bsdf, ('Alpha',), float(alpha))
        if emission is not None:
            set_socket(bsdf, ('Emission Color', 'Emission'), emission)
            set_socket(bsdf, ('Emission Strength',), float(emission_strength))
    mat.diffuse_color = (base[0], base[1], base[2], alpha)
    if alpha < 1.0:
        mat.blend_method = 'BLEND'
        mat.use_screen_refraction = True
    return mat


def assign(obj, mat):
    if obj and mat:
        obj.data.materials.append(mat)
    return obj


def shade(obj):
    try:
        bpy.context.view_layer.objects.active = obj
        obj.select_set(True)
        bpy.ops.object.shade_smooth()
        obj.select_set(False)
    except Exception:
        pass
    return obj


def add_uv(name, loc, scale, mat, segments=48, rings=24):
    bpy.ops.mesh.primitive_uv_sphere_add(segments=segments, ring_count=rings, radius=1.0, location=loc)
    obj = bpy.context.object
    obj.name = name
    obj.scale = scale
    assign(obj, mat)
    shade(obj)
    return obj


def add_cylinder_between(name, p1, p2, radius, mat, vertices=32):
    p1 = Vector(p1)
    p2 = Vector(p2)
    delta = p2 - p1
    length = max(0.001, delta.length)
    mid = p1 + delta * 0.5
    bpy.ops.mesh.primitive_cylinder_add(vertices=vertices, radius=radius, depth=length, location=mid)
    obj = bpy.context.object
    obj.name = name
    obj.rotation_euler = delta.to_track_quat('Z', 'Y').to_euler()
    assign(obj, mat)
    shade(obj)
    return obj


def add_box(name, loc, scale, mat):
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=loc)
    obj = bpy.context.object
    obj.name = name
    obj.scale = scale
    assign(obj, mat)
    shade(obj)
    return obj


def add_curve(name, points, mat, bevel=0.018):
    curve = bpy.data.curves.new(name=name, type='CURVE')
    curve.dimensions = '3D'
    curve.resolution_u = 16
    curve.bevel_depth = bevel
    curve.bevel_resolution = 4
    spline = curve.splines.new('POLY')
    spline.points.add(len(points)-1)
    for p, co in zip(spline.points, points):
        p.co = (float(co[0]), float(co[1]), float(co[2]), 1.0)
    obj = bpy.data.objects.new(name, curve)
    bpy.context.collection.objects.link(obj)
    assign(obj, mat)
    return obj


def add_hair_strand(name, offset, mat):
    x = offset
    return add_curve(
        name,
        [
            (x, 0.11, 3.62),
            (x * 1.05, 0.20, 3.34),
            (x * 1.18, 0.18, 3.06),
            (x * 1.05, 0.14, 2.76),
            (x * 0.92, 0.12, 2.52),
        ],
        mat,
        bevel=0.026,
    )


def look_at(obj, target):
    loc = Vector(obj.location)
    direction = Vector(target) - loc
    obj.rotation_euler = direction.to_track_quat('-Z', 'Y').to_euler()


def configure_gpu():
    backend = str(CFG.get('gpu_backend') or 'AUTO').upper()
    if backend in ('', 'AUTO'):
        preferred = ('OPTIX', 'CUDA', 'HIP', 'ONEAPI', 'METAL')
    else:
        preferred = (backend,)
    try:
        bpy.context.scene.render.engine = 'CYCLES'
        prefs = bpy.context.preferences.addons['cycles'].preferences
        for device_type in preferred:
            try:
                prefs.compute_device_type = device_type
                prefs.get_devices()
                enabled = 0
                for d in prefs.devices:
                    if getattr(d, 'type', '') != 'CPU':
                        d.use = True
                        enabled += 1
                    elif backend == 'CPU':
                        d.use = True
                if enabled or backend == 'CPU':
                    bpy.context.scene.cycles.device = 'GPU' if backend != 'CPU' else 'CPU'
                    CFG['gpu_selected'] = device_type
                    return
            except Exception:
                continue
    except Exception as exc:
        CFG['gpu_setup_error'] = str(exc)


def build_avatar():
    clear_scene()
    configure_gpu()

    skin = make_mat('SarahMemory_skin_from_concept', _color('skin', (0.86,0.62,0.50)), roughness=0.58)
    hair = make_mat('SarahMemory_magenta_hair_from_concept', _color('hair', (0.92,0.08,0.42)), roughness=0.32)
    suit = make_mat('SarahMemory_gloss_black_suit_from_concept', _color('suit', (0.005,0.008,0.012)), metallic=0.15, roughness=0.18)
    boot = make_mat('SarahMemory_gloss_black_boots', _color('boot', (0.005,0.006,0.008)), metallic=0.2, roughness=0.14)
    glow_col = _color('glow', (0.00,0.90,1.00))
    neon = make_mat('SarahMemory_cyan_emissive_lines_from_concept', glow_col, roughness=0.15, emission=glow_col, emission_strength=6.0)
    eye_mat = make_mat('SarahMemory_eye_black', (0.02,0.015,0.012,1), roughness=0.25)
    lip_mat = make_mat('SarahMemory_lip_soft', (0.75,0.18,0.28,1), roughness=0.45)

    # Humanoid proxy proportions based on the supplied concept sheet: T-pose, boots, long hair, neon suit.
    add_uv('torso_gloss_suit', (0, -0.01, 2.18), (0.42, 0.24, 0.74), suit)
    add_uv('pelvis_gloss_suit', (0, -0.01, 1.48), (0.36, 0.23, 0.30), suit)
    add_uv('chest_suit_form_L', (-0.17, -0.18, 2.42), (0.18, 0.08, 0.18), suit, 32, 16)
    add_uv('chest_suit_form_R', (0.17, -0.18, 2.42), (0.18, 0.08, 0.18), suit, 32, 16)
    add_cylinder_between('neck_skin', (0, -0.01, 2.82), (0, -0.01, 3.08), 0.10, skin)
    add_uv('head_skin', (0, -0.03, 3.36), (0.25, 0.20, 0.30), skin, 48, 24)

    # Arms in T-pose.
    for side, sx in [('L', -1), ('R', 1)]:
        add_uv(f'shoulder_{side}', (sx*0.43, -0.01, 2.62), (0.13,0.12,0.13), suit, 32, 16)
        add_cylinder_between(f'upper_arm_{side}_suit', (sx*0.44, -0.01, 2.58), (sx*0.92, -0.01, 2.55), 0.075, suit)
        add_cylinder_between(f'forearm_{side}_suit', (sx*0.92, -0.01, 2.55), (sx*1.40, -0.01, 2.53), 0.063, suit)
        add_uv(f'hand_{side}_skin', (sx*1.53, -0.03, 2.52), (0.105,0.045,0.055), skin, 24, 12)

    # Legs and boots.
    for side, sx in [('L', -1), ('R', 1)]:
        add_cylinder_between(f'thigh_{side}_suit', (sx*0.18, -0.01, 1.38), (sx*0.22, -0.01, 0.76), 0.115, suit)
        add_cylinder_between(f'calf_{side}_suit', (sx*0.22, -0.01, 0.76), (sx*0.20, -0.01, 0.24), 0.095, suit)
        add_box(f'platform_boot_{side}', (sx*0.20, -0.08, 0.08), (0.13, 0.26, 0.08), boot)
        add_box(f'boot_shaft_{side}', (sx*0.20, -0.01, 0.33), (0.12, 0.12, 0.20), boot)
        add_cylinder_between(f'heel_{side}_cyan_core', (sx*0.20, 0.09, 0.06), (sx*0.20, 0.09, -0.22), 0.025, neon, vertices=16)

    # Face details.
    add_uv('eye_L', (-0.085, -0.218, 3.39), (0.025,0.013,0.018), eye_mat, 16, 8)
    add_uv('eye_R', (0.085, -0.218, 3.39), (0.025,0.013,0.018), eye_mat, 16, 8)
    add_curve('soft_smile_lip', [(-0.075,-0.232,3.28), (-0.025,-0.245,3.255), (0.035,-0.245,3.255), (0.085,-0.232,3.28)], lip_mat, bevel=0.008)

    # Hair cap and flowing strands.
    add_uv('hair_cap_magenta', (0, 0.02, 3.49), (0.285,0.215,0.18), hair, 48, 18)
    for i, x in enumerate([-0.26,-0.21,-0.16,-0.11,-0.055,0.0,0.055,0.11,0.16,0.21,0.26]):
        add_hair_strand(f'magenta_hair_strand_{i:02d}', x, hair)

    # Cyan suit traces from the image: centerline, V chest, abdomen, limbs, boots.
    yfront = -0.285
    add_curve('neon_center_torso', [(0,yfront,2.72),(0,yfront,2.28),(0,yfront,1.78),(0,yfront,1.48)], neon, 0.012)
    add_curve('neon_chest_left_V', [(0,yfront,2.50),(-0.22,yfront,2.70),(-0.36,yfront,2.52)], neon, 0.011)
    add_curve('neon_chest_right_V', [(0,yfront,2.50),(0.22,yfront,2.70),(0.36,yfront,2.52)], neon, 0.011)
    add_curve('neon_waist_left', [(0,yfront,1.74),(-0.22,yfront,1.92),(-0.31,yfront,2.20)], neon, 0.011)
    add_curve('neon_waist_right', [(0,yfront,1.74),(0.22,yfront,1.92),(0.31,yfront,2.20)], neon, 0.011)
    add_curve('neon_pelvis_v', [(-0.23,yfront,1.62),(0,yfront,1.42),(0.23,yfront,1.62)], neon, 0.011)
    for side, sx in [('L', -1), ('R', 1)]:
        add_curve(f'neon_arm_{side}', [(sx*0.46,yfront,2.60),(sx*0.82,yfront,2.57),(sx*1.31,yfront,2.54)], neon, 0.010)
        add_curve(f'neon_leg_{side}', [(sx*0.18,yfront,1.32),(sx*0.22,yfront,0.80),(sx*0.20,yfront,0.28)], neon, 0.010)
        add_curve(f'neon_boot_{side}', [(sx*0.10,yfront,0.13),(sx*0.20,yfront,0.02),(sx*0.31,yfront,0.13)], neon, 0.010)

    # Rear cyan accents for back view compatibility.
    yback = 0.245
    add_curve('neon_back_spine', [(0,yback,2.68),(0,yback,2.18),(0,yback,1.55)], neon, 0.010)
    add_curve('neon_back_cross_L', [(-0.28,yback,2.22),(-0.05,yback,1.95),(-0.26,yback,1.68)], neon, 0.010)
    add_curve('neon_back_cross_R', [(0.28,yback,2.22),(0.05,yback,1.95),(0.26,yback,1.68)], neon, 0.010)

    # Stage/camera/lights so Blender preview opens usefully; export remains runtime-safe.
    bpy.ops.object.light_add(type='AREA', location=(0, -3.2, 4.2))
    bpy.context.object.name = 'avatar_key_light'
    bpy.context.object.data.energy = 500
    bpy.context.object.data.size = 4.0
    bpy.ops.object.camera_add(location=(0, -5.2, 2.45))
    cam = bpy.context.object
    look_at(cam, (0, -0.04, 1.90))
    bpy.context.scene.camera = cam

    # Metadata object marker.
    empty = bpy.data.objects.new('SarahMemory_Avatar_Metadata', None)
    empty['builder'] = 'SM-AVATARBUILD.py'
    empty['concept_image'] = CFG.get('concept_image', '')
    empty['design_note'] = 'Concept-inspired procedural GLB proxy: magenta hair, glossy black suit, cyan emissive traces, T-pose humanoid.'
    bpy.context.collection.objects.link(empty)

    out_blend = CFG.get('blend_path')
    if out_blend:
        try:
            bpy.ops.wm.save_as_mainfile(filepath=out_blend)
        except Exception as exc:
            CFG['blend_save_error'] = str(exc)

    out_glb = CFG['glb_path']
    os.makedirs(os.path.dirname(out_glb), exist_ok=True)
    bpy.ops.export_scene.gltf(
        filepath=out_glb,
        export_format='GLB',
        export_apply=True,
        export_yup=True,
        export_materials='EXPORT',
        export_animations=False,
    )

    if CFG.get('render_preview'):
        try:
            bpy.context.scene.render.resolution_x = 1200
            bpy.context.scene.render.resolution_y = 1600
            bpy.context.scene.render.filepath = CFG.get('preview_path')
            bpy.ops.render.render(write_still=True)
        except Exception as exc:
            CFG['preview_error'] = str(exc)


build_avatar()
